<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>levin</groupId>
  <artifactId>allvsall-sourceafis</artifactId>
  <version>1</version>
  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.machinezoo.sourceafis</groupId>
      <artifactId>sourceafis</artifactId>
      <version>3.18.1</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>copy-dependencies</goal></goals>
            <configuration><outputDirectory>${project.build.directory}/lib</outputDirectory></configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
